kind: ConfigMap
apiVersion: v1
metadata:
  name: "{{ .Release.Name }}-forms-yaml"
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: forms-yaml
    app.kubernetes.io/instance: server
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: ansibleforms
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/version: {{ .Chart.Version | quote }}
data:
  config: |
    {{ .Values.formsYaml | toYaml | nindent 4 }}
