apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: server
    app.kubernetes.io/instance: server
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: ansibleforms
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/version: {{ .Chart.Version | quote }}
data:
  DB_HOST: {{ .Values.dbHost | b64enc | quote }}
  DB_PORT: {{ .Values.dbPort | b64enc | quote }}
  DB_USER: {{ .Values.dbUser | b64enc | quote }}
  DB_PASSWORD: {{ .Values.dbPassword | b64enc | quote }}