version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - ./data/db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    image: ansibleforms
    restart: unless-stopped
    ports:
      - $WEBAPP_LOCAL_PORT:$WEBAPP_DOCKER_PORT
    env_file:
      - ./.env
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_PASSWORD
      - DB_PORT=$MYSQLDB_DOCKER_PORT
      - PORT=$WEBAPP_DOCKER_PORT
    stdin_open: true
    tty: true
    volumes:
      - ./data:/app/dist/persistent
