apiVersion: v1
kind: Service
metadata:
  namespace: ansibleforms
  name: server
  labels:
    app.kubernetes.io/name: server
    app.kubernetes.io/instance: server
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: ansibleforms
spec:
  type: LoadBalancer
  ports:
    - name: "8443"
      port: 8445
      targetPort: 8443
  selector:
    app.kubernetes.io/name: server
    app.kubernetes.io/instance: server
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  namespace: ansibleforms
  name: mysql
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: mysql
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: ansibleforms
spec:
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
  selector:
    app.kubernetes.io/name: mysql
