apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ansibleforms
  name: mysql
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: mysql
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: ansibleforms
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mysql
        app.kubernetes.io/instance: mysql
        app.kubernetes.io/component: database
        app.kubernetes.io/part-of: ansibleforms
    spec:
      containers:
        - image: mysql:5.7
          name: mysql
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ansibleforms-secrets
                  key: DB_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_DATABASE
                  name: ansibleforms-env
          resources:
            limits:
              cpu: "0.5"
              memory: 512Mi
            requests:
              cpu: "0.25"
              memory: 256Mi
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-persistent-storage
            - name: mysql-my-cnf
              mountPath: /etc/mysql/my.cnf
              subPath: my.cnf
      restartPolicy: Always
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: ansibleforms-mysql-pv-claim
        - name: mysql-my-cnf
          configMap:
            name: mysql-my-cnf
            items:
            - key: my.cnf
              path: my.cnf
status: {}
