apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: ansibleforms
  labels:
    app.kubernetes.io/name: server
    app.kubernetes.io/instance: server
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: ansibleforms
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: server
        app.kubernetes.io/instance: server
        app.kubernetes.io/component: server
        app.kubernetes.io/part-of: ansibleforms
    spec:
      containers:
        - image: ansibleguy/ansibleforms:latest
          name: server
          ports:
            - containerPort: 8443
          env:
            - name: PORT
              value: "8443"
            - name: DB_HOST
              value: mysql
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: ansibleforms-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ansibleforms-secrets
                  key: DB_PASSWORD
            - name: HTTPS
              value: "1"
            - name: LOG_CONSOLE_LEVEL
              valueFrom:
                configMapKeyRef:
                  key: LOG_CONSOLE_LEVEL
                  name: ansibleforms-env
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  key: LOG_LEVEL
                  name: ansibleforms-env
          resources:
            limits:
              cpu: "0.5"
              memory: 512Mi
            requests:
              cpu: "0.25"
              memory: 256Mi
          stdin: true
          tty: true
          volumeMounts:
            - mountPath: /app/dist/persistent
              name: server-persistent-storage
            - name: server-certificates
              mountPath: /app/dist/persistent/certificates/cert.pem
              subPath: cert.pem
            - name: server-certificates
              mountPath:  /app/dist/persistent/certificates/key.pem
              subPath: key.pem
      restartPolicy: Always
      volumes:
        - name: server-persistent-storage
          persistentVolumeClaim:
            claimName: ansibleforms-server-pv-claim
        - name: server-certificates
          configMap:
            name: server-certificates
            items:
            - key: cert.pem
              path: cert.pem
            - key: key.pem
              path: key.pem
status: {}
